### ISSUE TITLE
Failed Arduino/Python Readiness

### ISSUE THREAD

**Issue by chaws** [start-x/startx-src#10]
For some reason, when I hit 0 on the potentiometer the python program crashes:
Traceback (most recent call last):
  File "device/Comunication/main.py", line 96, in <module>
    main()
  File "device/Comunication/main.py", line 68, in main
    msp430.passives = sensor.Passives(msp430.serial, 0)
  File "/home/chaws/src/start-x/startx-src/device/Comunication/device.py", line 116, in **init**
    super(Passives, self).**init**(terminal)
  File "/home/chaws/src/start-x/startx-src/device/Comunication/device.py", line 65, in **init**
    super(Passive, self).**init**(terminal)
  File "/home/chaws/src/start-x/startx-src/device/Comunication/device.py", line 25, in **init**
    self.flush()
  File "/home/chaws/src/start-x/startx-src/device/Comunication/device.py", line 40, in flush
    return self.serial.readline()
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 475, in read
    raise SerialException('device reports readiness to read but returned no data (device disconnected or multiple access on port?)')
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

Also, the lights go of when I hit 0.

**Comment by chaws** [comment]
Another log error:
Traceback (most recent call last):
  File "device/Comunication/main.py", line 96, in <module>
    main()
  File "device/Comunication/main.py", line 76, in main
    sleep(0.01)
  File "device/Comunication/main.py", line 36, in write_file
    f.write(msp430['passives'])
  File "/home/chaws/src/start-x/startx-src/device/Comunication/msp430.py", line 66, in **getitem**
    raise e
serial.serialutil.SerialException: write failed: [Errno 5] Input/output error

**Comment by chaws** [comment]
My mistake hehe
