### ISSUE TITLE
Missing Python module "mock"

### ISSUE THREAD

**Issue by chaws** [start-x/startx-src#8]
Commands typed:
$ ./setup_development_environment.sh
$ make
& build/bikex
Traceback (most recent call last):
  File "device/scripts/main.py", line 11, in <module>
    from msp430 import MSP
  File "/home/chaws/src/start-x/startx-src/device/scripts/msp430.py", line 23, in <module>
    from mock import MagicMock
ImportError: No module named mock

**Comment by chaws** [comment]
Closed by @lucaskanashiro on Oct 1st with commit 68a0f10
